platform :ios, '8.0'

target 'SwiftySoundExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftySoundExample
  pod 'SwiftySound', :path => '..'

end
